/*REATE TABLE USERS (
        USER_ID SERIAL, 
        CREATE_TIME timestamp NOT NULL DEFAULT now(), 
        UPDATE_TIME timestamp,
        USER_NAME VARCHAR(200) NOT NULL
        );*/
--ALTER TABLE USERS ADD PRIMARY KEY(USER_ID);
--ALTER TABLE USERS ADD CONSTRAINT userNameConst UNIQUE (USER_NAME);
--ALTER TABLE USERS ALTER COLUMN CREATE_TIME SET NOT NULL;
--ALTER TABLE USERS ADD COLUMN EMAIL VARCHAR(255)
/*
CREATE TABLE MANAGED_APP (
        APP_ID SERIAL, 
        CREATE_TIME timestamp NOT NULL DEFAULT now(), 
        UPDATE_TIME timestamp,
        VERSION_NUMBER numeric(12) NOT NULL DEFAULT 1,
        APP_NAME VARCHAR(200),
        FILE_NAME VARCHAR(200) NOT NULL,
        DEPLOYMENT_PATH VARCHAR(2000) NOT NULL,
        COLUMN USER_ID INT NOT NULL      
);

*/


--ALTER TABLE MANAGED_APP ALTER COLUMN USER_ID SET NOT NULL;
--ALTER TABLE MANAGED_APP ALTER COLUMN CREATE_TIME SET  DEFAULT now()
--ALTER TABLE MANAGED_APP ADD FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
--INSERT INTO users ( user_name) VALUES ('test_user');

/*
CREATE TABLE PROFILE_MANAGED_APP (
        APP_ID INT NOT NULL,
        PI_ID INT NOT NULL
)
*/
--ALTER TABLE PROFILE_MANAGED_APP ADD FOREIGN KEY(APP_ID) REFERENCES MANAGED_APP(APP_ID)
--ALTER TABLE PROFILE_MANAGED_APP ADD FOREIGN KEY(PI_ID) REFERENCES PI_PROFILE(PI_ID)
--ALTER TABLE PROFILE_MANAGED_APP ADD CONSTRAINT uniqueIdsConst UNIQUE(APP_ID,PI_ID)
--ALTER TABLE PROFILE_MANAGED_APP DROP COLUMN CREATE_TIME

--ALTER TABLE PI_PROFILE ADD PRIMARY KEY(PI_ID);

--ALTER TABLE PI_PROFILE ADD column USER_ID INT NOT NULL DEFAULT 0
 --ALTER TABLE PI_PROFILE ADD FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
--update PI_PROFILE SET USER_ID = 1
--DELETE FROM users WHERE user_id = 4;

--select * from pg_available_extensions order by name desc;
--CREATE EXTENSION "uuid-ossp";
--select * from pg_extension;
--select uuid_generate_v4() as one;

--ALTER TABLE PI_PROFILE UPDATE COLUMN api_key DEFAULT

--update PI_PROFILE set api_key = uuid_generate_v4() where pi_id = 18
/*
CREATE TABLE APP_CONFIG (
        CONFIG_ID SERIAL, 
        CREATE_TIME timestamp NOT NULL DEFAULT now(), 
        UPDATE_TIME timestamp,
        CONFIG_KEY VARCHAR(255) NOT NULL,
        CONFIG_VALUE VARCHAR(255) NOT NULL
)
*/
--INSERT INTO app_config (config_key, config_value) VALUES ('key_name', 'value');
