/*REATE TABLE USERS (
        USER_ID SERIAL, 
        CREATE_TIME timestamp NOT NULL DEFAULT now(), 
        UPDATE_TIME timestamp,
        USER_NAME VARCHAR(200) NOT NULL
        );*/
--ALTER TABLE USERS ADD PRIMARY KEY(USER_ID);
--ALTER TABLE USERS ADD CONSTRAINT userNameConst UNIQUE (USER_NAME);
--ALTER TABLE USERS ALTER COLUMN CREATE_TIME SET NOT NULL;
--ALTER TABLE USERS ADD COLUMN EMAIL VARCHAR(255)
/*
CREATE TABLE MANAGED_APP (
        APP_ID SERIAL, 
        CREATE_TIME timestamp NOT NULL DEFAULT now(), 
        UPDATE_TIME timestamp,
        VERSION_NUMBER numeric(12) NOT NULL DEFAULT 1,
        APP_NAME VARCHAR(200),
        FILE_NAME VARCHAR(200) NOT NULL,
        DEPLOYMENT_PATH VARCHAR(2000) NOT NULL,
        COLUMN USER_ID INT NOT NULL      
);

*/


--ALTER TABLE MANAGED_APP ALTER COLUMN USER_ID SET NOT NULL;
--ALTER TABLE MANAGED_APP ALTER COLUMN CREATE_TIME SET  DEFAULT now()
--ALTER TABLE MANAGED_APP ADD FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
--INSERT INTO users ( user_name) VALUES ('test_user');

/*
CREATE TABLE PROFILE_MANAGED_APP (
        APP_ID INT NOT NULL,
        PI_ID INT NOT NULL,
        CREATE_TIME timestamp NOT NULL DEFAULT now()    
)
*/
--ALTER TABLE PROFILE_MANAGED_APP ADD FOREIGN KEY(APP_ID) REFERENCES MANAGED_APP(APP_ID)
--ALTER TABLE PROFILE_MANAGED_APP ADD FOREIGN KEY(PI_ID) REFERENCES PI_PROFILE(PI_ID)
--ALTER TABLE PROFILE_MANAGED_APP ADD CONSTRAINT uniqueIdsConst UNIQUE(APP_ID,PI_ID)


--ALTER TABLE PI_PROFILE ADD PRIMARY KEY(PI_ID);

--DELETE FROM users WHERE user_id = 4;
